parameters:
    cooklever_recipe.form.recipe_type.class: Cooklever\Bundle\RecipeBundle\Form\Type\RecipeType

services:
    cooklever_recipe.form.recipe_type:
        class: %cooklever_recipe.form.recipe_type.class%
        tags:
            - { name: form.type, alias: cooklever_bundle_recipe }
