fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

cooklever_app:
    resource: "@CookleverAppBundle/Controller/"
    type:     annotation

cooklever_recipe:
    resource: "@CookleverRecipeBundle/Controller/"
    type:     annotation
